//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherDescription", Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class WeatherDescription : object
    {
        
        private short WeatherIDField;
        
        private string DescriptionField;
        
        private string PictureURLField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short WeatherID
        {
            get
            {
                return this.WeatherIDField;
            }
            set
            {
                this.WeatherIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PictureURL
        {
            get
            {
                return this.PictureURLField;
            }
            set
            {
                this.PictureURLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForecastReturn", Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class ForecastReturn : object
    {
        
        private bool SuccessField;
        
        private string ResponseTextField;
        
        private string StateField;
        
        private string CityField;
        
        private string WeatherStationCityField;
        
        private WeatherWS.Forecast[] ForecastResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ResponseText
        {
            get
            {
                return this.ResponseTextField;
            }
            set
            {
                this.ResponseTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WeatherStationCity
        {
            get
            {
                return this.WeatherStationCityField;
            }
            set
            {
                this.WeatherStationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WeatherWS.Forecast[] ForecastResult
        {
            get
            {
                return this.ForecastResultField;
            }
            set
            {
                this.ForecastResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Forecast", Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class Forecast : object
    {
        
        private System.DateTime DateField;
        
        private short WeatherIDField;
        
        private string DesciptionField;
        
        private WeatherWS.temp TemperaturesField;
        
        private WeatherWS.POP ProbabilityOfPrecipiationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short WeatherID
        {
            get
            {
                return this.WeatherIDField;
            }
            set
            {
                this.WeatherIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desciption
        {
            get
            {
                return this.DesciptionField;
            }
            set
            {
                this.DesciptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public WeatherWS.temp Temperatures
        {
            get
            {
                return this.TemperaturesField;
            }
            set
            {
                this.TemperaturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public WeatherWS.POP ProbabilityOfPrecipiation
        {
            get
            {
                return this.ProbabilityOfPrecipiationField;
            }
            set
            {
                this.ProbabilityOfPrecipiationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="temp", Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class temp : object
    {
        
        private string MorningLowField;
        
        private string DaytimeHighField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MorningLow
        {
            get
            {
                return this.MorningLowField;
            }
            set
            {
                this.MorningLowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DaytimeHigh
        {
            get
            {
                return this.DaytimeHighField;
            }
            set
            {
                this.DaytimeHighField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POP", Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class POP : object
    {
        
        private string NighttimeField;
        
        private string DaytimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nighttime
        {
            get
            {
                return this.NighttimeField;
            }
            set
            {
                this.NighttimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Daytime
        {
            get
            {
                return this.DaytimeField;
            }
            set
            {
                this.DaytimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherReturn", Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class WeatherReturn : object
    {
        
        private bool SuccessField;
        
        private string ResponseTextField;
        
        private string StateField;
        
        private string CityField;
        
        private string WeatherStationCityField;
        
        private short WeatherIDField;
        
        private string DescriptionField;
        
        private string TemperatureField;
        
        private string RelativeHumidityField;
        
        private string WindField;
        
        private string PressureField;
        
        private string VisibilityField;
        
        private string WindChillField;
        
        private string RemarksField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ResponseText
        {
            get
            {
                return this.ResponseTextField;
            }
            set
            {
                this.ResponseTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WeatherStationCity
        {
            get
            {
                return this.WeatherStationCityField;
            }
            set
            {
                this.WeatherStationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public short WeatherID
        {
            get
            {
                return this.WeatherIDField;
            }
            set
            {
                this.WeatherIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Temperature
        {
            get
            {
                return this.TemperatureField;
            }
            set
            {
                this.TemperatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RelativeHumidity
        {
            get
            {
                return this.RelativeHumidityField;
            }
            set
            {
                this.RelativeHumidityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Wind
        {
            get
            {
                return this.WindField;
            }
            set
            {
                this.WindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Pressure
        {
            get
            {
                return this.PressureField;
            }
            set
            {
                this.PressureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Visibility
        {
            get
            {
                return this.VisibilityField;
            }
            set
            {
                this.VisibilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string WindChill
        {
            get
            {
                return this.WindChillField;
            }
            set
            {
                this.WindChillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cdyne.com/WeatherWS/", ConfigurationName="WeatherWS.WeatherSoap")]
    public interface WeatherSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/WeatherWS/GetWeatherInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherWS.GetWeatherInformationResponse> GetWeatherInformationAsync(WeatherWS.GetWeatherInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/WeatherWS/GetCityForecastByZIP", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherWS.GetCityForecastByZIPResponse> GetCityForecastByZIPAsync(WeatherWS.GetCityForecastByZIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/WeatherWS/GetCityWeatherByZIP", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherWS.GetCityWeatherByZIPResponse> GetCityWeatherByZIPAsync(WeatherWS.GetCityWeatherByZIPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherInformationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherInformation", Namespace="http://ws.cdyne.com/WeatherWS/", Order=0)]
        public WeatherWS.GetWeatherInformationRequestBody Body;
        
        public GetWeatherInformationRequest()
        {
        }
        
        public GetWeatherInformationRequest(WeatherWS.GetWeatherInformationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWeatherInformationRequestBody
    {
        
        public GetWeatherInformationRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherInformationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherInformationResponse", Namespace="http://ws.cdyne.com/WeatherWS/", Order=0)]
        public WeatherWS.GetWeatherInformationResponseBody Body;
        
        public GetWeatherInformationResponse()
        {
        }
        
        public GetWeatherInformationResponse(WeatherWS.GetWeatherInformationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class GetWeatherInformationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WeatherWS.WeatherDescription[] GetWeatherInformationResult;
        
        public GetWeatherInformationResponseBody()
        {
        }
        
        public GetWeatherInformationResponseBody(WeatherWS.WeatherDescription[] GetWeatherInformationResult)
        {
            this.GetWeatherInformationResult = GetWeatherInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityForecastByZIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityForecastByZIP", Namespace="http://ws.cdyne.com/WeatherWS/", Order=0)]
        public WeatherWS.GetCityForecastByZIPRequestBody Body;
        
        public GetCityForecastByZIPRequest()
        {
        }
        
        public GetCityForecastByZIPRequest(WeatherWS.GetCityForecastByZIPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class GetCityForecastByZIPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZIP;
        
        public GetCityForecastByZIPRequestBody()
        {
        }
        
        public GetCityForecastByZIPRequestBody(string ZIP)
        {
            this.ZIP = ZIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityForecastByZIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityForecastByZIPResponse", Namespace="http://ws.cdyne.com/WeatherWS/", Order=0)]
        public WeatherWS.GetCityForecastByZIPResponseBody Body;
        
        public GetCityForecastByZIPResponse()
        {
        }
        
        public GetCityForecastByZIPResponse(WeatherWS.GetCityForecastByZIPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class GetCityForecastByZIPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WeatherWS.ForecastReturn GetCityForecastByZIPResult;
        
        public GetCityForecastByZIPResponseBody()
        {
        }
        
        public GetCityForecastByZIPResponseBody(WeatherWS.ForecastReturn GetCityForecastByZIPResult)
        {
            this.GetCityForecastByZIPResult = GetCityForecastByZIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityWeatherByZIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityWeatherByZIP", Namespace="http://ws.cdyne.com/WeatherWS/", Order=0)]
        public WeatherWS.GetCityWeatherByZIPRequestBody Body;
        
        public GetCityWeatherByZIPRequest()
        {
        }
        
        public GetCityWeatherByZIPRequest(WeatherWS.GetCityWeatherByZIPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class GetCityWeatherByZIPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZIP;
        
        public GetCityWeatherByZIPRequestBody()
        {
        }
        
        public GetCityWeatherByZIPRequestBody(string ZIP)
        {
            this.ZIP = ZIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityWeatherByZIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityWeatherByZIPResponse", Namespace="http://ws.cdyne.com/WeatherWS/", Order=0)]
        public WeatherWS.GetCityWeatherByZIPResponseBody Body;
        
        public GetCityWeatherByZIPResponse()
        {
        }
        
        public GetCityWeatherByZIPResponse(WeatherWS.GetCityWeatherByZIPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.cdyne.com/WeatherWS/")]
    public partial class GetCityWeatherByZIPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WeatherWS.WeatherReturn GetCityWeatherByZIPResult;
        
        public GetCityWeatherByZIPResponseBody()
        {
        }
        
        public GetCityWeatherByZIPResponseBody(WeatherWS.WeatherReturn GetCityWeatherByZIPResult)
        {
            this.GetCityWeatherByZIPResult = GetCityWeatherByZIPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface WeatherSoapChannel : WeatherWS.WeatherSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class WeatherSoapClient : System.ServiceModel.ClientBase<WeatherWS.WeatherSoap>, WeatherWS.WeatherSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WeatherSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WeatherSoapClient.GetBindingForEndpoint(endpointConfiguration), WeatherSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WeatherSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WeatherSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherWS.GetWeatherInformationResponse> WeatherWS.WeatherSoap.GetWeatherInformationAsync(WeatherWS.GetWeatherInformationRequest request)
        {
            return base.Channel.GetWeatherInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherWS.GetWeatherInformationResponse> GetWeatherInformationAsync()
        {
            WeatherWS.GetWeatherInformationRequest inValue = new WeatherWS.GetWeatherInformationRequest();
            inValue.Body = new WeatherWS.GetWeatherInformationRequestBody();
            return ((WeatherWS.WeatherSoap)(this)).GetWeatherInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherWS.GetCityForecastByZIPResponse> WeatherWS.WeatherSoap.GetCityForecastByZIPAsync(WeatherWS.GetCityForecastByZIPRequest request)
        {
            return base.Channel.GetCityForecastByZIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherWS.GetCityForecastByZIPResponse> GetCityForecastByZIPAsync(string ZIP)
        {
            WeatherWS.GetCityForecastByZIPRequest inValue = new WeatherWS.GetCityForecastByZIPRequest();
            inValue.Body = new WeatherWS.GetCityForecastByZIPRequestBody();
            inValue.Body.ZIP = ZIP;
            return ((WeatherWS.WeatherSoap)(this)).GetCityForecastByZIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherWS.GetCityWeatherByZIPResponse> WeatherWS.WeatherSoap.GetCityWeatherByZIPAsync(WeatherWS.GetCityWeatherByZIPRequest request)
        {
            return base.Channel.GetCityWeatherByZIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherWS.GetCityWeatherByZIPResponse> GetCityWeatherByZIPAsync(string ZIP)
        {
            WeatherWS.GetCityWeatherByZIPRequest inValue = new WeatherWS.GetCityWeatherByZIPRequest();
            inValue.Body = new WeatherWS.GetCityWeatherByZIPRequestBody();
            inValue.Body.ZIP = ZIP;
            return ((WeatherWS.WeatherSoap)(this)).GetCityWeatherByZIPAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WeatherSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WeatherSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WeatherSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsf.cdyne.com/WeatherWS/Weather.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WeatherSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsf.cdyne.com/WeatherWS/Weather.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WeatherSoap,
            
            WeatherSoap12,
        }
    }
}
